name: 'On-Premises Deploy'
description: 'Deploy apps to an on-premises virtual machine.'
inputs:
  source-path:
    description: 'Source path for application'
    required: true
    default: '.'
  az-service-bus-connection-string:
    description: 'Connection string to an Azure service bus namespace for sending notifications'
    required: false
  az-storage-connection-string:
    description: 'Connection string to an Azure storage account for holding build artifacts'
    required: false
  dest-host:
    description: 'A unique identifier for the destination host'
    required: false
  dest-host-env:
    description: 'Semi-colon separated key/value pairs to be injected into the host environment'
    required: false
  message:
    description: 'A message to be logged ... backwards'
    required: false
outputs:
  archive-path: 
    description: 'The path to the zipped build artifact'
runs:
  using: 'node16'
  main: 'dist/index.js'