name: 'On-Premises Deploy'
description: 'Deploy apps to an on-premises virtual machine.'
inputs:
  az-service-bus-connection-string:
    description: 'Connection string to an Azure service bus namespace for sending notifications'
    required: true
  az-storage-connection-string:
    description: 'Connection string to an Azure storage account for holding build artifacts'
    required: true
  source-path:
    description: 'Source path for application'
    required: true
    default: '.'
  host:
    description: 'A unique identifier for the host'
    required: true
  app-name:
    description: 'The name of the app to deploy'
    required: true
  environment:
    description: 'A JSON object containing key/value pairs for environment variables to update'
    required: false
  app_secrets: 
    description: 'A JSON object containing key/value pairs for app secrets to update'
    required: false
outputs:
  archive-path: 
    description: 'The path to the zipped build artifact'
runs:
  using: 'node16'
  main: 'dist/index.js'